version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - DB_CONNECT=mongodb://mongo:27017/mydatabase
      - TOKEN_SECRET=hello
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
